# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 655)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background: black;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 380, 240))
        self.frame.setStyleSheet("background-color: Black;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(80, 20, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 85, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 131, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_2.setObjectName("label_2")
        self.first_currency = QtWidgets.QComboBox(parent=self.centralwidget)
        self.first_currency.setGeometry(QtCore.QRect(30, 230, 320, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.first_currency.setFont(font)
        self.first_currency.setStyleSheet("margin: 10px;\n"
"padding: 8px;\n"
"border: 2px solid #7B2BDD;\n"
"border-radius: 30;\n"
"color: rgb(255, 85, 0);")
        self.first_currency.setObjectName("first_currency")
        self.first_currency.addItem("")
        self.first_currency.addItem("")
        self.first_currency.addItem("")
        self.first_currency.addItem("")
        self.second_currency = QtWidgets.QComboBox(parent=self.centralwidget)
        self.second_currency.setGeometry(QtCore.QRect(30, 390, 320, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.second_currency.setFont(font)
        self.second_currency.setStyleSheet("margin: 10px;\n"
"padding: 8px;\n"
"border: 2px solid #7B2BDD;\n"
"border-radius: 30;\n"
"color: rgb(255, 85, 0);")
        self.second_currency.setObjectName("second_currency")
        self.second_currency.addItem("")
        self.second_currency.addItem("")
        self.second_currency.addItem("")
        self.second_currency.addItem("")
        self.input_currency = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_currency.setGeometry(QtCore.QRect(30, 310, 320, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.input_currency.setFont(font)
        self.input_currency.setStyleSheet("margin: 10px;\n"
"border: 2px solid #7B2BDD;\n"
"border-radius: 30;\n"
"color: rgb(255, 85, 0);")
        self.input_currency.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_currency.setObjectName("input_currency")
        self.output_currency = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_currency.setGeometry(QtCore.QRect(30, 470, 320, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.output_currency.setFont(font)
        self.output_currency.setStyleSheet("margin: 10px;\n"
"border: 2px solid #7B2BDD;\n"
"border-radius: 30;\n"
"color: rgb(255, 85, 0);")
        self.output_currency.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_currency.setObjectName("output_currency")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 560, 320, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: rgb(255, 85, 0);\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Сurrency converter"))
        self.first_currency.setItemText(0, _translate("MainWindow", "RUB"))
        self.first_currency.setItemText(1, _translate("MainWindow", "USD"))
        self.first_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.first_currency.setItemText(3, _translate("MainWindow", "JPY"))
        self.second_currency.setItemText(0, _translate("MainWindow", "USD"))
        self.second_currency.setItemText(1, _translate("MainWindow", "GBP"))
        self.second_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.second_currency.setItemText(3, _translate("MainWindow", "JPY"))
        self.pushButton.setText(_translate("MainWindow", "Convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
